-- MySQL Script generated by MySQL Workbench
-- Thu Oct  7 15:46:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user`;
USE `user`;
-- -----------------------------------------------------
-- Table `Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Categoria` ;

CREATE TABLE IF NOT EXISTS `Categoria` (
  `idCategoria` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Senhas_idSenhas` INT NOT NULL,
  PRIMARY KEY (`idCategoria`),
  CONSTRAINT `fk_Categoria_Senhas1`
    FOREIGN KEY (`Senhas_idSenhas`)
    REFERENCES `Senhas` (`idSenhas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Categoria_Senhas1_idx` ON `Categoria` (`Senhas_idSenhas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Conteudo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Conteudo` ;

CREATE TABLE IF NOT EXISTS `Conteudo` (
  `idConteudo` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Data` DATETIME NULL,
  `Titulo` VARCHAR(45) NULL,
  `Url` VARCHAR(45) NULL,
  `Autor` VARCHAR(45) NULL,
  `Descrição` VARCHAR(100) NULL,
  `Conteúdo` VARCHAR(200) NULL,
  PRIMARY KEY (`idConteudo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Senhas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Senhas` ;

CREATE TABLE IF NOT EXISTS `Senhas` (
  `idSenhas` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `SenhaArmazenada` VARCHAR(18) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idSenhas`),
  CONSTRAINT `fk_Senhas_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Senhas_Usuario_idx` ON `Senhas` (`Usuario_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `idUsuario` INT NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Senha` VARCHAR(18) NULL,
  `Nome` VARCHAR(45) NULL,
  `Sobrenome` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario_has_Conteudo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario_has_Conteudo` ;

CREATE TABLE IF NOT EXISTS `Usuario_has_Conteudo` (
  `Usuario_idUsuario` INT NOT NULL,
  `Conteudo_idConteudo` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Conteudo_idConteudo`),
  CONSTRAINT `fk_Usuario_has_Conteudo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Conteudo_Conteudo1`
    FOREIGN KEY (`Conteudo_idConteudo`)
    REFERENCES `Conteudo` (`idConteudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_has_Conteudo_Conteudo1_idx` ON `Usuario_has_Conteudo` (`Conteudo_idConteudo` ASC) VISIBLE;

CREATE INDEX `fk_Usuario_has_Conteudo_Usuario1_idx` ON `Usuario_has_Conteudo` (`Usuario_idUsuario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
